global:
  scrape_interval: 15s # How often to ask for data

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ticket-service'
    static_configs:
      - targets: ['ticket-service:5000']
 
  - job_name: 'support-service'
    static_configs:
      - targets: ['support-service:5000']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5000'] # Internal container name and port

  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:5000']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
